version: '3'
services:
  kafka-kraft-1:
    image: confluentinc/cp-kafka:7.5.2
    container_name: kafka-kraft-1
    hostname: kafka-kraft-1
    ports:
      # - "9101:9101" # JMX port
      - "19092:9092" # Kafka port for external connections
      # - "29092:29092" # Kafka port for internal connections
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:19092"
      # KAFKA_JMX_PORT: "9101"
      # KAFKA_JMX_HOSTNAME: "localhost"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-kraft-1:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-kraft-1:29092,CONTROLLER://kafka-kraft-1:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT_HOST"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
