version: '3.1'

services:

  mysql:
    ports:
      - 3307:3306
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - kafka_default

networks:
  kafka_default:
    external: true